In [1]:
import numpy as np


---
# VIDEO: A zoo of matrices
---


In [2]:
# square vs. rectangular
S = np.random.randn(5, 5)
R = np.random.randn(5, 2) # 5 rows, 2 columns
print(S), print(' ')
print(R)

# identity
I = np.eye(3)
print(I), print(' ')

# zeros
Z = np.zeros((4, 4))
print(Z), print(' ')

# diagonal
D = np.diag([1, 2, 3, 5, 2])
print(D), print(' ')

# create triangular matrix from full matrices
S = np.random.randn(5, 5)
U = np.triu(S)
L = np.tril(S)
print(L), print(' ')

# concatenate matrices (sizes must match!)
A = np.random.randn(3, 2)
B = np.random.randn(3, 4)
C = np.concatenate((A, B), axis=1)
print(C)

[[ 1.551711    1.09355148 -1.39935686  0.08479648 -0.56924962]
 [ 0.67914062  1.48443618 -0.36129496 -3.49189179  0.93620437]
 [ 0.98824665  1.14597453 -1.93401894 -0.32229466  0.71810412]
 [-1.26281856  0.64087275  1.37853682 -0.61149779  3.36755471]
 [ 0.25955285 -0.42450796  1.94708921 -1.73140487 -0.64804356]]
 
[[-0.85642935 -1.47372496]
 [-0.66382683 -1.02487681]
 [-1.17557458  0.43429762]
 [ 1.20878469  0.18249544]
 [-0.05238678 -0.27221082]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]
 
[[-0.40075063  0.          0.          0.          0.        ]
 [-0.79059177  0.84656176  0.          0.          0.        ]
 [-0.49735065 -1.49395417  0.87268081  0.          0.        ]
 [-0.91904872 -1.33959583 -0.27400759 -0.09310235  0.        ]
 [ 1.13620533  0.84029043 -0.43351214  0.39166118  2.03597942]]
 
[[-4.95114992e-01  4.67585664e-01  1.36695101e+00  1.56348


---
# VIDEO: Matrix addition and subtraction
---


In [3]:
# create random matrices
A = np.random.randn(5, 4)
B = np.random.randn(5, 3)
C = np.random.randn(5, 4)

A+C

# "shifting" a matrix
l = .03 # lambda
N = 5  # size of square matrix
D = np.random.randn(N, N) # can only shift a square matrix

Ds = D + l*np.eye(N)

print(D)
print(' ')
print(Ds)

[[ 0.61526228  0.40285913  1.66628079  0.98378391 -0.73382504]
 [ 1.39641388  1.27833311 -1.31338584  0.92932628 -2.20679474]
 [-1.03048675 -0.65566207  0.83266321 -1.07297465 -0.28371196]
 [-2.12449468 -0.8589108   1.83451679 -1.55149064  0.02178024]
 [ 1.90381232 -0.66985792  1.64224008 -0.39883866 -0.137818  ]]
 
[[ 0.64526228  0.40285913  1.66628079  0.98378391 -0.73382504]
 [ 1.39641388  1.30833311 -1.31338584  0.92932628 -2.20679474]
 [-1.03048675 -0.65566207  0.86266321 -1.07297465 -0.28371196]
 [-2.12449468 -0.8589108   1.83451679 -1.52149064  0.02178024]
 [ 1.90381232 -0.66985792  1.64224008 -0.39883866 -0.107818  ]]



---
# VIDEO: Matrix-scalar multiplication
---


In [4]:
# define matrix and scalar
M = np.array([[1, 2], [2, 5]])
s = 2

# pre- and post-multiplication is the same:
print(M*s)
print(s*M)


[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]


# VIDEO: Transpose

In [5]:
M = np.array([[1, 2, 3],
              [2, 3, 4]])

print(M), print('')
print(M.T), print('') # one transpose
print(M.T.T), print('') # double-transpose returns the original matrix

# can also use the function transpose
print(np.transpose(M))

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]


In [6]:
# warning! be careful when using complex matrices
C = np.array([[4+1j, 3, 2-4j]])

print(C), print('')
print(C.T), print('')
print(np.transpose(C)), print('')

# Note: In MATLAB, the transpose is the Hermitian transpose; 
#       in Python, you need to call the Hermitian explicitly by first converting from an array into a matrix
print(np.matrix(C).H) # note the sign flips!


[[4.+1.j 3.+0.j 2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]



---
# VIDEO: Diagonal and trace
---


In [7]:
M = np.round(6*np.random.randn(4, 4))
print(M), print()

# notice the two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print(d)
print(D)

# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum(np.diag(M))
print(tr,tr2)

[[-5. -9. 11. -3.]
 [ 7. -2. -3. -6.]
 [ 5. -4. -3.  1.]
 [-1. -1. -4.  3.]]

[-5. -2. -3.  3.]
[[-5.  0.  0.  0.]
 [ 0. -2.  0.  0.]
 [ 0.  0. -3.  0.]
 [ 0.  0.  0.  3.]]
-7.0 -7.0



---
# VIDEO: Broadcasting matrix arithmetic
---


In [8]:
# create a matrix
A = np.reshape(np.arange(1, 13), (3, 4), 'F') # F=column, C=row

# and two vectors
r = [10, 20, 30, 40]
c = [100, 200, 300]

print(A)
print()
print(r)
print()
print(c)
print()

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]

[10, 20, 30, 40]

[100, 200, 300]



In [9]:
# broadcast on the rows
print(A+r), print(' ')

# broadcast on the columns
# print(A+c)
print(A+np.reshape(c,(len(c),1))) # only works for explicit column vectors


[[11 24 37 50]
 [12 25 38 51]
 [13 26 39 52]]
 
[[101 104 107 110]
 [202 205 208 211]
 [303 306 309 312]]
